/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as RafflesIndexRouteImport } from './routes/raffles/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as GumballsIndexRouteImport } from './routes/gumballs/index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions/index'
import { Route as StatsProfit_lossRouteImport } from './routes/stats/profit_loss'
import { Route as StatsAnalyticsRouteImport } from './routes/stats/analytics'
import { Route as RafflesCreate_rafflesRouteImport } from './routes/raffles/create_raffles'
import { Route as RafflesIdRouteImport } from './routes/raffles/$id'
import { Route as ProfileUser_profileRouteImport } from './routes/profile/user_profile'
import { Route as GumballsPreview_gumballRouteImport } from './routes/gumballs/preview_gumball'
import { Route as GumballsCreate_gumballsRouteImport } from './routes/gumballs/create_gumballs'
import { Route as GumballsIdRouteImport } from './routes/gumballs/$id'
import { Route as AuctionsCreate_auctionsRouteImport } from './routes/auctions/create_auctions'
import { Route as AuctionsIdRouteImport } from './routes/auctions/$id'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const RafflesIndexRoute = RafflesIndexRouteImport.update({
  id: '/raffles/',
  path: '/raffles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const GumballsIndexRoute = GumballsIndexRouteImport.update({
  id: '/gumballs/',
  path: '/gumballs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsProfit_lossRoute = StatsProfit_lossRouteImport.update({
  id: '/stats/profit_loss',
  path: '/stats/profit_loss',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsAnalyticsRoute = StatsAnalyticsRouteImport.update({
  id: '/stats/analytics',
  path: '/stats/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const RafflesCreate_rafflesRoute = RafflesCreate_rafflesRouteImport.update({
  id: '/raffles/create_raffles',
  path: '/raffles/create_raffles',
  getParentRoute: () => rootRouteImport,
} as any)
const RafflesIdRoute = RafflesIdRouteImport.update({
  id: '/raffles/$id',
  path: '/raffles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUser_profileRoute = ProfileUser_profileRouteImport.update({
  id: '/profile/user_profile',
  path: '/profile/user_profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GumballsPreview_gumballRoute = GumballsPreview_gumballRouteImport.update({
  id: '/gumballs/preview_gumball',
  path: '/gumballs/preview_gumball',
  getParentRoute: () => rootRouteImport,
} as any)
const GumballsCreate_gumballsRoute = GumballsCreate_gumballsRouteImport.update({
  id: '/gumballs/create_gumballs',
  path: '/gumballs/create_gumballs',
  getParentRoute: () => rootRouteImport,
} as any)
const GumballsIdRoute = GumballsIdRouteImport.update({
  id: '/gumballs/$id',
  path: '/gumballs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsCreate_auctionsRoute = AuctionsCreate_auctionsRouteImport.update({
  id: '/auctions/create_auctions',
  path: '/auctions/create_auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/create_auctions': typeof AuctionsCreate_auctionsRoute
  '/gumballs/$id': typeof GumballsIdRoute
  '/gumballs/create_gumballs': typeof GumballsCreate_gumballsRoute
  '/gumballs/preview_gumball': typeof GumballsPreview_gumballRoute
  '/profile/user_profile': typeof ProfileUser_profileRoute
  '/raffles/$id': typeof RafflesIdRoute
  '/raffles/create_raffles': typeof RafflesCreate_rafflesRoute
  '/stats/analytics': typeof StatsAnalyticsRoute
  '/stats/profit_loss': typeof StatsProfit_lossRoute
  '/auctions': typeof AuctionsIndexRoute
  '/gumballs': typeof GumballsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/raffles': typeof RafflesIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/create_auctions': typeof AuctionsCreate_auctionsRoute
  '/gumballs/$id': typeof GumballsIdRoute
  '/gumballs/create_gumballs': typeof GumballsCreate_gumballsRoute
  '/gumballs/preview_gumball': typeof GumballsPreview_gumballRoute
  '/profile/user_profile': typeof ProfileUser_profileRoute
  '/raffles/$id': typeof RafflesIdRoute
  '/raffles/create_raffles': typeof RafflesCreate_rafflesRoute
  '/stats/analytics': typeof StatsAnalyticsRoute
  '/stats/profit_loss': typeof StatsProfit_lossRoute
  '/auctions': typeof AuctionsIndexRoute
  '/gumballs': typeof GumballsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/raffles': typeof RafflesIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/create_auctions': typeof AuctionsCreate_auctionsRoute
  '/gumballs/$id': typeof GumballsIdRoute
  '/gumballs/create_gumballs': typeof GumballsCreate_gumballsRoute
  '/gumballs/preview_gumball': typeof GumballsPreview_gumballRoute
  '/profile/user_profile': typeof ProfileUser_profileRoute
  '/raffles/$id': typeof RafflesIdRoute
  '/raffles/create_raffles': typeof RafflesCreate_rafflesRoute
  '/stats/analytics': typeof StatsAnalyticsRoute
  '/stats/profit_loss': typeof StatsProfit_lossRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/gumballs/': typeof GumballsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/raffles/': typeof RafflesIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/auctions/$id'
    | '/auctions/create_auctions'
    | '/gumballs/$id'
    | '/gumballs/create_gumballs'
    | '/gumballs/preview_gumball'
    | '/profile/user_profile'
    | '/raffles/$id'
    | '/raffles/create_raffles'
    | '/stats/analytics'
    | '/stats/profit_loss'
    | '/auctions'
    | '/gumballs'
    | '/profile'
    | '/raffles'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-found'
    | '/auctions/$id'
    | '/auctions/create_auctions'
    | '/gumballs/$id'
    | '/gumballs/create_gumballs'
    | '/gumballs/preview_gumball'
    | '/profile/user_profile'
    | '/raffles/$id'
    | '/raffles/create_raffles'
    | '/stats/analytics'
    | '/stats/profit_loss'
    | '/auctions'
    | '/gumballs'
    | '/profile'
    | '/raffles'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/not-found'
    | '/auctions/$id'
    | '/auctions/create_auctions'
    | '/gumballs/$id'
    | '/gumballs/create_gumballs'
    | '/gumballs/preview_gumball'
    | '/profile/user_profile'
    | '/raffles/$id'
    | '/raffles/create_raffles'
    | '/stats/analytics'
    | '/stats/profit_loss'
    | '/auctions/'
    | '/gumballs/'
    | '/profile/'
    | '/raffles/'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
  AuctionsCreate_auctionsRoute: typeof AuctionsCreate_auctionsRoute
  GumballsIdRoute: typeof GumballsIdRoute
  GumballsCreate_gumballsRoute: typeof GumballsCreate_gumballsRoute
  GumballsPreview_gumballRoute: typeof GumballsPreview_gumballRoute
  ProfileUser_profileRoute: typeof ProfileUser_profileRoute
  RafflesIdRoute: typeof RafflesIdRoute
  RafflesCreate_rafflesRoute: typeof RafflesCreate_rafflesRoute
  StatsAnalyticsRoute: typeof StatsAnalyticsRoute
  StatsProfit_lossRoute: typeof StatsProfit_lossRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  GumballsIndexRoute: typeof GumballsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RafflesIndexRoute: typeof RafflesIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffles/': {
      id: '/raffles/'
      path: '/raffles'
      fullPath: '/raffles'
      preLoaderRoute: typeof RafflesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gumballs/': {
      id: '/gumballs/'
      path: '/gumballs'
      fullPath: '/gumballs'
      preLoaderRoute: typeof GumballsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/profit_loss': {
      id: '/stats/profit_loss'
      path: '/stats/profit_loss'
      fullPath: '/stats/profit_loss'
      preLoaderRoute: typeof StatsProfit_lossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/analytics': {
      id: '/stats/analytics'
      path: '/stats/analytics'
      fullPath: '/stats/analytics'
      preLoaderRoute: typeof StatsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffles/create_raffles': {
      id: '/raffles/create_raffles'
      path: '/raffles/create_raffles'
      fullPath: '/raffles/create_raffles'
      preLoaderRoute: typeof RafflesCreate_rafflesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffles/$id': {
      id: '/raffles/$id'
      path: '/raffles/$id'
      fullPath: '/raffles/$id'
      preLoaderRoute: typeof RafflesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/user_profile': {
      id: '/profile/user_profile'
      path: '/profile/user_profile'
      fullPath: '/profile/user_profile'
      preLoaderRoute: typeof ProfileUser_profileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gumballs/preview_gumball': {
      id: '/gumballs/preview_gumball'
      path: '/gumballs/preview_gumball'
      fullPath: '/gumballs/preview_gumball'
      preLoaderRoute: typeof GumballsPreview_gumballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gumballs/create_gumballs': {
      id: '/gumballs/create_gumballs'
      path: '/gumballs/create_gumballs'
      fullPath: '/gumballs/create_gumballs'
      preLoaderRoute: typeof GumballsCreate_gumballsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gumballs/$id': {
      id: '/gumballs/$id'
      path: '/gumballs/$id'
      fullPath: '/gumballs/$id'
      preLoaderRoute: typeof GumballsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/create_auctions': {
      id: '/auctions/create_auctions'
      path: '/auctions/create_auctions'
      fullPath: '/auctions/create_auctions'
      preLoaderRoute: typeof AuctionsCreate_auctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  AuctionsIdRoute: AuctionsIdRoute,
  AuctionsCreate_auctionsRoute: AuctionsCreate_auctionsRoute,
  GumballsIdRoute: GumballsIdRoute,
  GumballsCreate_gumballsRoute: GumballsCreate_gumballsRoute,
  GumballsPreview_gumballRoute: GumballsPreview_gumballRoute,
  ProfileUser_profileRoute: ProfileUser_profileRoute,
  RafflesIdRoute: RafflesIdRoute,
  RafflesCreate_rafflesRoute: RafflesCreate_rafflesRoute,
  StatsAnalyticsRoute: StatsAnalyticsRoute,
  StatsProfit_lossRoute: StatsProfit_lossRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  GumballsIndexRoute: GumballsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RafflesIndexRoute: RafflesIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
